import type { Metadata } from "next";
import {
  Barlow_Condensed,
  Instrument_Serif,
  Geist,
  Noto_Serif,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import TelemetryNavbar from "@/components/TelemetryNavbar";

const notoSerif = Noto_Serif({subsets:['latin'],variable:'--font-serif'});

const geist = Geist({ subsets: ["latin"], variable: "--font-geo" });

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const displayTech = localFont({
  src: "./fonts/Display.otf",
  variable: "--font-tech",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
              "h-full",
              "dark",
              "antialiased",
              barlowCondensed.variable,
              instrumentSerif.variable,
              displayTech.variable,
              geist.variable,
              notoSerif.variable)}
    >
      <body className="min-h-full flex flex-col">
        <TelemetryNavbar />
        {children}
      </body>
    </html>
  );
}
